### ISSUE TITLE
 Refactoring for Improved Readability and Reliability

### ISSUE THREAD

**Issue by vantage-ola** [vantage-ola/track-now#7]
Current backend code exhibits redundancy. Aim to enhance readability and maintainability by introducing modular functions. Additionally, prioritize  documentation and robust testing for increased reliability and exception handling( #3 )

**Comment by Dozie2001** [comment]
Can you give more context?
I would like to be assigned to this task but I need more context here

**Comment by vantage-ola** [comment]
> Can you give more context? I would like to be assigned to this task but I need more context here

sorry, i just saw this :( ,  if  you take a look at the backend, it is kinda messy , no exception handling etc...but the backend needs to be finished to start working on it...

**Comment by Dozie2001** [comment]
So what part would you like me to finish? What is the implementation now.Will take a look at the codebase tomorrow night but it would be nice if you could give a direction

**Comment by vantage-ola** [comment]
> So what part would you like me to finish? What is the implementation now.Will take a look at the codebase tomorrow night but it would be nice if you could give a direction

Can you take a look at issue #8

**Comment by vantage-ola** [comment]
there's always room for improvement lol
