### ISSUE TITLE
`api/collection/<collection_id>/collections` routes GET all entries` returns empty erray even if the entry does not exist

### ISSUE THREAD

**Issue by vantage-ola** [vantage-ola/track-now#8]
```
#python3 `\backend\app.py`
list_of_drivers_id= [laptime_dict.get('driver_id') for laptime_dict in tracks_laptime_dicts

        # Use $in to find tracks with matching track_ids
drivers = db.drivers.find({'id': {'$in': list_of_drivers_id}}, {'_id': False})
driver_dicts = [driver for driver in drivers]
if drivers:
        # Convert the result to a list of dictionaries
    return jsonify(driver_dicts)
        #else wouldnt even work, it rathers returns empty array 
```
if the entry doesnt exist, we should return 'entry not found'. it returns [ ], when querying the server.

**Comment by Dozie2001** [comment]
Why is the condition ? 
``` python
 if drivers:
        # Convert the result to a list of dictionaries
    return jsonify(driver_dicts)
``` and not:
``` python
 if driver_dicts:
        # Convert the result to a list of dictionaries
    return jsonify(driver_dicts) 
``` 
Since driver_dicts is a list of drivers it would check the condition will check if the driver exist with the id(indirectly) exit if not and the list is empty it would return "Entry not found"

**Comment by vantage-ola** [comment]
> Why is the condition ?
> 
> ```python
>  if drivers:
>         # Convert the result to a list of dictionaries
>     return jsonify(driver_dicts)
> ``` and not:
> ``` python
>  if driver_dicts:
>         # Convert the result to a list of dictionaries
>     return jsonify(driver_dicts) 
> ```
> 
> Since driver_dicts is a list of drivers it would check the condition will check if the driver exist with the id(indirectly) exit if not and the list is empty it would return "Entry not found"

yeah you are very correct, i will work on implementing the fix :+1:
